version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: patient-service-db
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5000:5432"   # Host:Container port mapping
    volumes:
      - ./docker_postgresql:/var/lib/postgresql/data  # Bind mount
    networks:
      - internal_network  # Connecting this service to the custom network
    
  authentication:
    image: postgres:latest
    container_name: auth-service-db
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5001:5432"   # Host:Container port mapping
    volumes:
      - ./docker_postgres_auth:/var/lib/postgresql/data  # Bind mount
    networks:
      - internal_network  # Connecting this service to the custom network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
    ports:
      - "9092:9092"  
      - "9094:9094"   
    networks:
      - internal_network

  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile  # Path to Dockerfile in patient-service
    container_name: patient-service
    image: patient-service:latest  
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db  # Connecting to PostgreSQL
      SPRING_DATASOURCE_USERNAME: admin_user  
      SPRING_DATASOURCE_PASSWORD: password  
      SPRING_JPA_HIBERNATE_DDL_AUTO: update  # JPA setting for auto schema update
      SPRING_SQL_INIT_MODE: always  
      BILLING_SERVICE_ADDRESS: billing-service # Address of the billing service auto map from below
      BILLING_SERVICE_GRPC_PORT: 9001  # gRPC port for billing service
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092  # Kafka bootstrap server address
    networks:
      - internal_network  # Connects to the same network as postgres

  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile  
    container_name: billing-service
    image: billing-service:latest  
    ports:
      - "4001:4001"  # Host:Container port mapping
      - "9001:9001"  # Host:Container port mapping for gRPC
    networks:
      - internal_network  

  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: Dockerfile  
    container_name: analytics-service
    image: analytics-service:latest  
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092  # Kafka bootstrap server address
    ports:
      - "4002:4002" 
    networks:
      - internal_network  
  
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile  
    container_name: api-gateway
    image: api-gateway:latest 
    ports:
      - "4004:4004" 
    networks:
      - internal_network  
      
networks:
  internal_network:
    driver: bridge  # Use the bridge driver for internal communication
