server:
    port: 4004

spring:
    cloud:
        gateway:
            routes:
                -   id: auth-service-route
                    uri: http://host.docker.internal:4005
                    predicates:
                        - Path=/auth/**
                    filters:
                        - StripPrefix=1
                    ## REST CLIENT --> http://localhost:4004/auth/login
                    ## API GATEWAY --> http://localhost:4005/login

                -   id: patient-service-route
                    uri: http://host.docker.internal:4000
                    predicates:
                        - Path=/api/patients/**
                    filters:
                        - StripPrefix=1
                        - JwtValidation    ## go to jwt gateway filter class
                    ## REST CLIENT --> http://localhost:4004/api/patients
                    ## API GATEWAY --> http://localhost:4004/patients/
                    ## PATIENT SERVICE (SPRING BOOT APP) --> /patients --> Patients array

                -   id: api-docs-patient-route
                    uri: http://host.docker.internal:4000
                    predicates:
                        - Path=/api-docs/patients
                    filters:
                        - RewritePath=/api-docs/patients, /v3/api-docs
                    ## REST CLIENT --> http://localhost:4004/api-docs/patients
                    ## API GATEWAY --> http://localhost:4004/v3/api-docs

                -   id: api-docs-auth-route
                    uri: http://host.docker.internal:4005
                    predicates:
                        - Path=/api-docs/auth
                    filters:
                        - RewritePath=/api-docs/auth, /v3/api-docs
