### create patient
POST http://localhost:4004/api/patients
Content-Type: application/json

{
    "name": "lixing66",
    "email" : "lixing66@example.com",
    "address" : "123 Main St, Springfield, USA",
    "dateOfBirth" : "1990-01-01",
    "registeredDate" : "2023-10-01"
}